# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

# The main page title that gets displayed on all pages on the top bar and
# within the meta information.
title: 'SUSE Hawk'

# The provider will get displayed on the footer of each page to show who
# provides this nice project ;-)
provider: 'Copyright &copy; 2009-2016 SUSE, LLC'
