# Sample config for Prometheus.

global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node_exporter_webui
    static_configs:
      - targets: ['{{ pillar['ip_node_0'] }}:9100']

  - job_name: node_exporter_node1
    static_configs:
      - targets: ['{{ pillar['ip_node_1'] }}:9100']

  - job_name: node_exporter_node2
    static_configs:
      - targets: ['{{ pillar['ip_node_2'] }}:9100']

  - job_name: pacemaker_exporter_webui
    static_configs:
      - targets: ['{{ pillar['ip_node_0'] }}:9356']

  # - job_name: pacemaker_exporter_node1
  #   static_configs:
  #     - targets: ['{{ pillar['ip_node_1'] }}:9356']

  # - job_name: pacemaker_exporter_node2
  #   static_configs:
  #     - targets: ['{{ pillar['ip_node_2'] }}:9356']
